### PR TITLE
Convert code to use Microsoft Graph SDK

### PR DESCRIPTION
**Pull request by jussihi**
This commit converts the code to use Graph SDK for PowerShell instead of using self-written request handling.

PowerShell 7+ recommended.

I decided to work on this myself since I had some time at work. At least adding new contacts work now flawlessly. There might still be some problems with contact updates, but I will continue testing today.

### CODE REVIEW

**Comment by JeshuaEdgar** [comment]
Thanks for your work! I was going to abstain from using the Graph SDK because it is notoriously slow when compared to raw REST requests, but in some cases you cannot go around it. As for the accented characters, somehow through the SDK they are not lost. I have made some changes in my code that I wanted to push but have not yet, let me commit them to your fork and we can merge it into the master.

**Comment by jussihi** [comment]
> Thanks for your work! I was going to abstain from using the Graph SDK because it is notoriously slow when compared to raw REST requests, but in some cases you cannot go around it. As for the accented characters, somehow through the SDK they are not lost. I have made some changes in my code that I wanted to push but have not yet, let me commit them to your fork and we can merge it into the master.

Hmm. If you prefer using raw REST request, maybe the code should be separated into two different branches, or have a user option to choose between Raw REST/Graph SDK. I see it is slow, it takes almost a minute to sync 700 contacts. And when we multiply it by 700 for all users in my org... 😄

I can move this to "graph-sdk" branch if you would like, and then in the future the branches could be merged if there is a programmatically implemented switch between the two options.

**Comment by jussihi** [comment]
For reasons beyond my comprehension, I cannot make the delta comparison working (for the list for what users/contacts require updating) (line 41 on `Module\Public\func_Sync-GALContacts.ps1`). So my changes don't have that working (yet).

**Comment by JeshuaEdgar** [comment]
I have been able to make the delta comparrison work succesfully using a little internal function, you can review it if you want.

I agree, it is probably best to create another branch with graph-sdk and merge it at a later state.

One thing to note with the latest version is that accented charachters are somehow not working properly, only on creation, the displayname does not get returned when querying in the contactfolder. However, this does seem to work with the Graph SDK, so you might want to swap it out in your testing/production instead of the native REST request in `func_Get-FolderContact.ps1`.

Let me know how it goes!

**Comment by jussihi** [comment]
> I agree, it is probably best to create another branch with graph-sdk and merge it at a later state.

Sure. I will close this PR for now and report back about the delta fixes tomorrow. I think that I will implement the SDK switch and create another PR with it hopefully tomorrow :)

**Pull request closed without merging**
